### ISSUE TITLE
EmulationExit exception is protected

### ISSUE THREAD

**Issue by boriel** [kosarev/zx#17]
If one wants to catch `EmulationExit` exception, s/he has to write:
```python
from zx._except import EmulationExit
```
The member `_except` is prefixed with `_` and marked as "protected".
Of course it works, but many linters complain with "accessing a protected member".
Could it be possible to have exceptions in the `zx` namespace? (I can issue you a PR :) )

**Comment by kosarev** [comment]
Yeah, I wasn't sure about the name of the exception and decided to postpone making it public for now. Looking at the standard Python 3 exceptions, we already have `SystemExit` and `GeneratorExit`, and `EmulationExit` is not quite an interrupt kind of exception (we in fact might want to have `EmulationInterrupt` in the future, I can imagine), so time showed no concerns about the name, it seems. Will prepare a patch in a minute. Thanks. : )

**Comment by kosarev** [comment]
@boriel Done. Please check on your side.

**Comment by boriel** [comment]
Works ok!!
Thanks! :)
